routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

//основые страницы сайта
Route::group(['prefix' => '/', 'middleware' => ['referral']], function(){

    Route::get('/', function () {
        return view('landing');
    });
    Route::get('/dropshipping', function () {
        return view('landingDropshipping');
    });
    Route::get('/about', function () {
        return view('about');
    });
    Route::get('/tariff', function () {
        return view('tariff');
    });


    Route::group(['prefix' => 'blog'], function () {
        Route::get('/', 'WebsiteController@articles')->name('articles');
        Route::match(['get', 'post'], '/{id}', 'WebsiteController@article')->name('article');
    });

});

Route::get('/telegram/'.\App\Telegram\TelegramBot::$token, 'TelegramBotController@index')->name('telegram.api');


Route::get('/mail', 'MailController@send')->name('mail.send');


Route::post('/create-consultation-request', 'WebsiteController@createConsultationRequest')->name('createConsultationRequest');

Auth::routes();

//личный кабинет
Route::get('/home/new', 'HomeController@new')->middleware('auth')->name('agent.new');
Route::group(['prefix' => 'home', 'middleware' => ['auth', 'userOnline']], function(){ //, 'documents'

    Route::get('/', 'HomeController@index')->name('agent.home');
    Route::get('/website/create', 'Agent\WebsiteController@createPage')->name('agent.website.create');
    Route::get('/website/create/setup', 'Agent\WebsiteController@setup')->name('agent.website.create.setup');
    Route::post('/website/create/setup/categories', 'Agent\WebsiteController@selectCategories')->name('agent.website.create.setup.selectCategories');

    Route::group(['prefix' => 'website', 'middleware' => ['isUserWebsite']], function () {
        Route::get('/{id}', 'Agent\WebsiteController@index')->name('agent.website');
        Route::get('/{id}/generate-token', 'Agent\WebsiteController@generateApiToken')->name('agent.website.generateApiToken');
        Route::post('/{id}/set-markup', 'Agent\WebsiteController@setOptMarkup')->name('agent.website.setOptMarkup');
        Route::match(['get', 'post'], '/{id}/analytics', 'Agent\ProductController@analytics')->name('agent.product.analytics');
        Route::match(['get', 'post'], '/{id}/yml', 'Agent\ProductController@yml')->name('agent.product.yml');
    });

    Route::group(['prefix' => 'wallet'], function() {
        Route::get('/', 'Agent\WalletController@index')->name('agent.wallet');
        Route::post('/', 'Agent\WalletController@createWidtdrawRequest')->name('agent.wallet.createWidtdrawRequest');
    });

    Route::group(['prefix' => 'settings'], function() {
        Route::get('/documents', 'Agent\SettingsController@documents')->name('agent.settings.documents');
        Route::post('/documents-update', 'Agent\SettingsController@documentsUpdate')->name('agent.settings.documents.update');
        Route::get('/change-juristic', 'Agent\SettingsController@changeJuristic')->name('agent.settings.changeJuristic');
    });

    Route::get('/partners', 'HomeController@partners')->name('agent.partners');
});

//админка
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'isAdmin', 'userOnline']], function(){
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::get('/orders', 'AdminController@orders')->name('orders');
    Route::get('/order/{id}', 'OrderController@index')->name('order');
    Route::post('/order/{id}', 'OrderController@addHistory')->name('order_post');
    Route::get('/order/{id}/print', 'OrderController@print')->name('order.print');
    Route::get('/websites', 'Admin\WebsiteController@list')->name('admin.websites');
    Route::match(['get', 'post'], '/website/{id}', 'Admin\WebsiteController@edit')->name('admin.website.edit');
    Route::match(['get', 'post'], '/website/{id}/categories', 'Admin\WebsiteController@categories')->name('admin.website.categories');
    Route::post('/website/{id}/prolong', 'Admin\WebsiteController@prolong')->name('admin.website.prolong');
    Route::get('/widthdraw-requests', 'AdminController@widthdrawRequests')->name('admin.widthdrawRequests');
    Route::get('/widthdraw-request/{id}', 'AdminController@widthdrawRequest')->name('admin.widthdrawRequest');
    Route::post('/widthdraw-request/{id}', 'AdminController@updateWidthdrawRequestStatus')->name('admin.updateWidthdrawRequestStatus');
    Route::get('/git', 'AdminController@git')->name('admin.git');
    Route::post('/git', 'AdminController@git')->name('admin.git.post');
    Route::get('/users', 'Admin\UserController@list')->name('admin.users');
    Route::get('/user/{id}', 'Admin\UserController@index')->name('admin.user');
    Route::get('/categories', 'Admin\CategoryController@list')->name('admin.categories');
    Route::match(['get', 'post'], '/category/{id?}', 'Admin\CategoryController@edit')->name('admin.category.edit');
    Route::get('/category/{id}/delete', 'Admin\CategoryController@delete')->name('admin.category.delete');
    Route::get('/consultations', 'Admin\ConsultationController@list')->name('admin.consultations');
    Route::match(['get', 'post'], '/consultation/{id}', 'Admin\ConsultationController@index')->name('admin.consultation');

    Route::group(['prefix' => 'product'], function () {
        Route::match(['get', 'post'], '/list', 'Admin\ProductController@list')->name('admin.product.list');
    });
    Route::group(['prefix' => 'pricelist'], function () {
        Route::get('/lapsi', 'Admin\PricelistController@lapsi')->name('admin.pricelist.lapsi');
        Route::group(['prefix' => 'yml'], function () {
            Route::match(['get', 'post'], '/', 'Admin\PricelistController@index')->name('admin.pricelist.index');
            Route::match(['get', 'post'], '/categories/{id}', 'Admin\PricelistController@categories')->name('admin.pricelist.categories');
            Route::match(['get', 'post'], '/products/{id}', 'Admin\PricelistController@uploadProducts')->name('admin.pricelist.products');
        });
        Route::get('/upload-updates', 'Admin\PricelistController@uploadUpdates')->name('admin.pricelist.uploadUpdates');
    });
    Route::group(['prefix' => 'articles'], function () {
        Route::get('/', 'Admin\BlogController@list')->name('admin.articles');
        Route::match(['get', 'post'], '/{id}', 'Admin\BlogController@edit')->name('admin.articles.edit');
    });

    Route::get('/ajax/order', 'OrderController@ajaxGetList')->name('ajax_order_list');
    Route::post('/ajax/getMonthsOrders', 'HomeController@getMonthsOrders')->name('dashboard.getMonthsOrders');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $table = 'articles';

    //получение автора
    public static $authors = [];
    public function getAuthorNameAttribute() {
        if(!isset(self::$authors[$this->author_id]))
            self::$authors[$this->author_id] = User::find($this->author_id);
        return self::$authors[$this->author_id]->first_name.' '.self::$authors[$this->author_id]->second_name;
    }

    public function getTextAttribute() {
        if(isset($this->attributes['text'])) {
            $text = $this->attributes['text'];
            $pos = strripos($text, '<p data-');
            if($pos)
                $text = substr($text, 0, $pos);
        } else
            $text = '';
        return $text;
    }

    public function category() {
        return $this->belongsTo('App\ArticleCategory', 'category_id');
    }

    public function tags() {
        return $this->belongsToMany('App\ArticleTag', 'article_to_tag', 'article_id', 'tag_id');
    }

    public function comments() {
        return $this->hasMany('App\ArticleComment', 'article_id');
    }
}

class ArticleCategory extends Model
{
    protected $table = 'article_category';

    public $timestamps = false;

    public function articles() {
        return $this->hasMany('App\Article', 'category_id');
    }
}

class ArticleTag extends Model
{
    protected $table = 'article_tag';

    public $timestamps = false;

    public function articles() {
        return $this->belongsToMany('App\Article', 'article_to_tag', 'tag_id', 'article_id');
    }
}

class ArticleToTag extends Model
{
    protected $table = 'article_to_tag';

    public $timestamps = false;
}

class ArticleComment extends Model
{
    protected $table = 'article_comment';
}

resources/views/about.blade.php
@extends('layouts.landingapp')

@push('title') О компании гипо @endpush

@section('content')
  <section class="hero-wrap hero-wrap-2" style="background-image: url('/img/landing/head-1.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-center justify-content-center">
        <div class="col-md-9 ftco-animate text-center">
          <h1 class="mb-2 bread">Контактная информация</h1>
          <p class="breadcrumbs"><span class="mr-2"><a href="/">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Контакты <i class="ion-ios-arrow-forward"></i></span></p>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section contact-section bg-light">
    <div class="container">
      <div class="row d-flex mb-5 contact-info">
        <div class="col-md-12 mb-4">
          <h2 class="h4">Контакты</h2>
        </div>
        <div class="w-100"></div>
        <div class="col-md-4">
          <p><span>Адрес:</span> г.Санкт-Петербург, ул.Магнитогорская 51 лит.Р, офис 201</p>
        </div>
        <div class="col-md-4">
          <p><span>Телефон:</span> <a href="tel://88129517871">8 812 951-78-71</a></p>
        </div>
        <div class="col-md-4">
          <p><span>E-mail:</span> <a href="mailto:info@gipo.ru">info@gipo.ru</a></p>
        </div>
      </div>
      <div class="row d-flex mb-5 contact-info">
        <div class="col-md-12 mb-4">
          <h2 class="h4">Юридическая информация</h2>
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-lg-6">
          <p>Общество с ограниченной ответственностью "ГИПО"</p>
          <p>ИНН: 7801656750</p>
          <p>КПП: 780101001</p>
          <p>ОГРН: 1187847379312</p>
          <p>ОКПО: 35034426</p>
          <p>Юр.адрес: Почтовый индекс 199155, г. Санкт-Петербург, ул. Уральская, дом 12, корпус 5 литер Д, помещение 87 офис 87</p>
          <p>Р/С: № 40702810755000041015</p>
          <p>К/сч: № 30101810500000000653</p>
          <p>БИК 044030653</p>
          <p>ПАО Сбербанк, 191023, г. Санкт-Петербург, ул. Садовая дом 28-30 корпус 3 ИНН банка 7707083893, КПП: 784243001, ОГРН: 1027700132195, ОКПО: 09171401</p>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/article.blade.php
@extends('layouts.landingapp')

@push('title') {{ $article->title }} | гипо.ру @endpush

@section('content')
  <section class="hero-wrap hero-wrap-2 overflow-hidden">
    <div class="overlay"
         style="background-image: url('{{ $article->image or '/img/landing/head-1.jpg' }}');filter: blur(5px);-webkit-background-size: cover;background-size: cover;background-position: center;"
         data-stellar-background-ratio="0.5"></div>
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-center justify-content-center">
        <div class="col-md-9 ftco-animate text-center">
          <h1 class="mb-2 bread">{{ $article->title }}</h1>
          <p class="breadcrumbs"><span class="mr-2"><a href="/">Главная <i class="ion-ios-arrow-forward"></i></a></span>
            <span><a href="{{ route('articles') }}">Статьи <i class="ion-ios-arrow-forward"></i></a></span></p>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 ftco-animate">
          <p>
            <img src="{{ $article->image }}" alt="" class="img-fluid">
          </p>
          <div class="text-dark" style="font-size: 20px">
            {!! $article->text !!}
          </div>
          <div class="tag-widget post-tag-container mb-5 mt-5">
            <div class="tagcloud">
              @foreach($article->tags as $tag)
                <a href="{{ route('articles', ['tag' => $tag->id]) }}" class="tag-cloud-link">{{ $tag->name }}</a>
              @endforeach
            </div>
          </div>
          <div><a class="mr-3"><span
                  class="icon-calendar"></span> {{ Date::parse($article->created_at)->format('d, M. Y') }}</a>
            <a><span class="icon-person"></span> {{ $article->author_name }}</a></div>
          {{--<div class="about-author d-flex p-4 bg-light">--}}
          {{--<div class="bio mr-5">--}}
          {{--<img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">--}}
          {{--</div>--}}
          {{--<div class="desc">--}}
          {{--<h3>George Washington</h3>--}}
          {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus--}}
          {{--voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique,--}}
          {{--inventore eos fugit cupiditate numquam!</p>--}}
          {{--</div>--}}
          {{--</div>--}}
          <div class="pt-5 mt-5" id="comments">
            <h3 class="mb-5 h4 font-weight-bold">{{ $comments_count }} Комментариев</h3>
            <ul class="comment-list">
              @include('partials.user_comment', ['comments' => $article->comments, 'parent_id' => ''])
            </ul>

            <div class="comment-form-wrap pt-5">
              <h3 class="mb-5 h4 font-weight-bold">Оставить комментарий
                <span class="btn btn-dark btn-sm ml-3 px-3" id="cancel-reply" style="display: none;">Отменить ответ</span></h3>
              <form action="" class="p-5 bg-light" id="left_comment" method="POST">
                {{ csrf_field() }}
                <div class="form-group" style="display: none;" id="reply_to_area">
                  <label for="reply_to">Ответить на комментарий</label>
                  <input type="text" class="form-control" id="reply_to" name="reply_to" readonly>
                </div>
                @if(!Auth::user())
                  <div class="form-group">
                    <label for="name">Имя *</label>
                    <input type="text" class="form-control" id="name" name="name" minlength="3" maxlength="50" required>
                  </div>
                @endif
                <div class="form-group">
                  <label for="message">Комментарий</label>
                  <textarea name="message" id="message" cols="30" rows="10" class="form-control" minlength="6"
                            maxlength="500" required></textarea>
                </div>
                <div class="form-group">
                  <input type="submit" value="Оставить комментарий" class="btn py-3 px-4 btn-primary">
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-4 sidebar ftco-animate">
          <div class="sidebar-box ftco-animate">
            <h3>Категория</h3>
            <ul class="categories">
              <li>
                <a href="{{ route('articles') }}">Все статьи</a>
              </li>
              @foreach($categories as $category)
                <li>
                  <a href="{{ route('articles', ['category' => $category->id]) }}">{{ $category->name }} <span>({{ $category->articles->count() }})</span></a>
                </li>
              @endforeach
            </ul>
          </div>
          <div class="sidebar-box ftco-animate">
            <h3>Популярные статьи</h3>
            @foreach($populars as $article)
              <div class="block-21 mb-4 d-flex">
                <a href="{{ route('article', $article->id) }}" class="blog-img mr-4"
                   style="background-image: url('{{ $article->image }}');"></a>
                <div class="text">
                  <h3 class="heading"><a href="{{ route('article', $article->id) }}">{{ $article->title }}</a>
                  </h3>
                  <div class="meta">
                    <div><a><span
                            class="icon-calendar"></span> {{ Date::parse($article->created_at)->format('d, M. Y') }}</a>
                    </div>
                    <div><a><span class="icon-person"></span> {{ $article->author_name }}</a></div>
                    <div><a><span class="icon-chat"></span> {{ $article->comments->count() }}</a></div>
                  </div>
                </div>
              </div>
            @endforeach
          </div>
          <div class="sidebar-box ftco-animate">
            <h3>Облако тегов</h3>
            <ul class="tagcloud m-0 p-0">
              @foreach($tags as $tag)
                <a href="{{ route('articles', ['tag' => $tag->id]) }}" class="tag-cloud-link">{{ $tag->name }}</a>
              @endforeach
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

@push('styles')
  <style>
    .article-category > a {
      color: #b3b3b3;
      font-size: 13px;
    }

    .comment-list li .comment-body .meta {
      color: #8e8e8e;
    }
  </style>
@endpush

@push('scripts')
  <script>
      $('.reply-button').click(function () {
          var to = $(this).data('comment_id');
          $('#reply_to').val(to);
          $('#reply_to_area').show();
          $('#cancel-reply').show();
          $('html, body').animate({
              scrollTop: $("#left_comment").offset().top - 200
          }, 500);
      });
      $('#cancel-reply').click(function () {
          $('#reply_to').val('');
          $('#reply_to_area').hide();
          $('#cancel-reply').hide();
      });
  </script>
@endpush

resources/views/articles.blade.php
@extends('layouts.landingapp')

@push('title') Статьи | гипо.ру @endpush

@section('content')
  <section class="hero-wrap hero-wrap-2" style="background-image: url('https://images.unsplash.com/photo-1517976384346-3136801d605d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80');"
           data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-center justify-content-center">
        <div class="col-md-9 ftco-animate text-center">
          <h1 class="mb-2 bread">Статьи</h1>
          <p class="breadcrumbs"><span class="mr-2"><a href="/">Главная <i class="ion-ios-arrow-forward"></i></a></span>
            <span>Статьи <i class="ion-ios-arrow-forward"></i></span></p>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="row">
            @foreach($articles as $article)
              <div class="col-md-6 ftco-animate">
                <div class="blog-entry">
                  <a href="{{ route('article', $article->id) }}" class="block-20"
                     style="background-image: url('{{ $article->image }}');"></a>
                  <div class="text d-flex py-4">
                    <div class="meta mb-3">
                      <div><a>{{ Date::parse($article->created_at)->format('d, M. Y') }}</a></div>
                      <div><a>{{ $article->author_name }}</a></div>
                      <div><a class="meta-chat"><span class="icon-chat"></span> {{ $article->comments->count() }}</a></div>
                    </div>
                    <div class="desc pl-3">
                      @if(!isset(request()->category))
                        <div class="article-category"><a class="">{{ $article->category->name or '' }}</a></div>
                      @endif
                      <h3 class="heading"><a href="{{ route('article', $article->id) }}">{{ $article->title }}</a></h3>
                    </div>
                  </div>
                </div>
              </div>
            @endforeach
          </div>
          <div class="row no-gutters my-5">
            {{--<div class="col text-center">--}}
            {{--<div class="block-27">--}}
            {{--<ul>--}}
            {{--<li><a href="#">&lt;</a></li>--}}
            {{--<li class="active"><span>1</span></li>--}}
            {{--<li><a href="#">2</a></li>--}}
            {{--<li><a href="#">3</a></li>--}}
            {{--<li><a href="#">4</a></li>--}}
            {{--<li><a href="#">5</a></li>--}}
            {{--<li><a href="#">&gt;</a></li>--}}
            {{--</ul>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{ $articles->appends($_GET)->links() }}
          </div>
        </div>
        <div class="col-lg-4 sidebar ftco-animate">
          <div class="sidebar-box ftco-animate">
            <h3>Категория</h3>
            <ul class="categories">
              <li>
                <a href="{{ route('articles') }}">Все статьи</a>
              </li>
              @foreach($categories as $category)
                <li>
                  <a href="{{ route('articles', ['category' => $category->id]) }}">{{ $category->name }} <span>({{ $category->articles->count() }})</span></a>
                </li>
              @endforeach
            </ul>
          </div>
          <div class="sidebar-box ftco-animate">
            <h3>Популярные статьи</h3>
            @foreach($populars as $article)
              <div class="block-21 mb-4 d-flex">
                <a href="{{ route('article', $article->id) }}" class="blog-img mr-4" style="background-image: url('{{ $article->image }}');"></a>
                <div class="text">
                  <h3 class="heading"><a href="{{ route('article', $article->id) }}">{{ $article->title }}</a>
                  </h3>
                  <div class="meta">
                    <div><a><span
                            class="icon-calendar"></span> {{ Date::parse($article->created_at)->format('d, M. Y') }}</a>
                    </div>
                    <div><a><span class="icon-person"></span> {{ $article->author_name }}</a></div>
                    <div><a><span class="icon-chat"></span> {{ $article->comments->count() }}</a></div>
                  </div>
                </div>
              </div>
            @endforeach
          </div>
          <div class="sidebar-box ftco-animate">
            <h3>Облако тегов</h3>
            <ul class="tagcloud m-0 p-0">
              @foreach($tags as $tag)
                <a href="{{ route('articles', ['tag' => $tag->id]) }}" class="tag-cloud-link">{{ $tag->name }}</a>
              @endforeach
            </ul>
          </div>
          {{--<div class="sidebar-box ftco-animate">--}}
          {{--<h3>Архив</h3>--}}
          {{--<ul class="categories">--}}
          {{--<li><a href="#">December 2018 <span>(30)</span></a></li>--}}
          {{--<li><a href="#">Novemmber 2018 <span>(20)</span></a></li>--}}
          {{--<li><a href="#">September 2018 <span>(6)</span></a></li>--}}
          {{--<li><a href="#">August 2018 <span>(8)</span></a></li>--}}
          {{--</ul>--}}
          {{--</div>--}}
          {{--<div class="sidebar-box ftco-animate">--}}
          {{--<h3>Paragraph</h3>--}}
          {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate--}}
          {{--quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos--}}
          {{--fugit cupiditate numquam!</p>--}}
          {{--</div>--}}
        </div>
      </div>
    </div>
  </section>
@endsection

@push('styles')
  <style>
    .article-category > a {
      color: #b3b3b3;
      font-size: 13px;
    }
  </style>
@endpush