routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

//основые страницы сайта
Route::group(['prefix' => '/', 'middleware' => ['referral']], function(){

    Route::get('/', function () {
        return view('landing');
    });
    Route::get('/dropshipping', function () {
        return view('landingDropshipping');
    });
    Route::get('/about', function () {
        return view('about');
    });
    Route::get('/tariff', function () {
        return view('tariff');
    });


    Route::group(['prefix' => 'blog'], function () {
        Route::get('/', 'WebsiteController@articles')->name('articles');
        Route::match(['get', 'post'], '/{id}', 'WebsiteController@article')->name('article');
    });

});

Route::get('/telegram/'.\App\Telegram\TelegramBot::$token, 'TelegramBotController@index')->name('telegram.api');


Route::get('/mail', 'MailController@send')->name('mail.send');


Route::post('/create-consultation-request', 'WebsiteController@createConsultationRequest')->name('createConsultationRequest');

Auth::routes();

//личный кабинет
Route::get('/home/new', 'HomeController@new')->middleware('auth')->name('agent.new');
Route::group(['prefix' => 'home', 'middleware' => ['auth', 'userOnline']], function(){ //, 'documents'

    Route::get('/', 'HomeController@index')->name('agent.home');
    Route::get('/website/create', 'Agent\WebsiteController@createPage')->name('agent.website.create');
    Route::get('/website/create/setup', 'Agent\WebsiteController@setup')->name('agent.website.create.setup');
    Route::post('/website/create/setup/categories', 'Agent\WebsiteController@selectCategories')->name('agent.website.create.setup.selectCategories');

    Route::group(['prefix' => 'website', 'middleware' => ['isUserWebsite']], function () {
        Route::get('/{id}', 'Agent\WebsiteController@index')->name('agent.website');
        Route::get('/{id}/generate-token', 'Agent\WebsiteController@generateApiToken')->name('agent.website.generateApiToken');
        Route::post('/{id}/set-markup', 'Agent\WebsiteController@setOptMarkup')->name('agent.website.setOptMarkup');
        Route::match(['get', 'post'], '/{id}/analytics', 'Agent\ProductController@analytics')->name('agent.product.analytics');
        Route::match(['get', 'post'], '/{id}/yml', 'Agent\ProductController@yml')->name('agent.product.yml');
    });

    Route::group(['prefix' => 'wallet'], function() {
        Route::get('/', 'Agent\WalletController@index')->name('agent.wallet');
        Route::post('/', 'Agent\WalletController@createWidtdrawRequest')->name('agent.wallet.createWidtdrawRequest');
    });

    Route::group(['prefix' => 'settings'], function() {
        Route::get('/documents', 'Agent\SettingsController@documents')->name('agent.settings.documents');
        Route::post('/documents-update', 'Agent\SettingsController@documentsUpdate')->name('agent.settings.documents.update');
        Route::get('/change-juristic', 'Agent\SettingsController@changeJuristic')->name('agent.settings.changeJuristic');
    });

    Route::get('/partners', 'HomeController@partners')->name('agent.partners');
});

//админка
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'isAdmin', 'userOnline']], function(){
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::get('/orders', 'AdminController@orders')->name('orders');
    Route::get('/order/{id}', 'OrderController@index')->name('order');
    Route::post('/order/{id}', 'OrderController@addHistory')->name('order_post');
    Route::get('/order/{id}/print', 'OrderController@print')->name('order.print');
    Route::get('/websites', 'Admin\WebsiteController@list')->name('admin.websites');
    Route::match(['get', 'post'], '/website/{id}', 'Admin\WebsiteController@edit')->name('admin.website.edit');
    Route::match(['get', 'post'], '/website/{id}/categories', 'Admin\WebsiteController@categories')->name('admin.website.categories');
    Route::post('/website/{id}/prolong', 'Admin\WebsiteController@prolong')->name('admin.website.prolong');
    Route::get('/widthdraw-requests', 'AdminController@widthdrawRequests')->name('admin.widthdrawRequests');
    Route::get('/widthdraw-request/{id}', 'AdminController@widthdrawRequest')->name('admin.widthdrawRequest');
    Route::post('/widthdraw-request/{id}', 'AdminController@updateWidthdrawRequestStatus')->name('admin.updateWidthdrawRequestStatus');
    Route::get('/git', 'AdminController@git')->name('admin.git');
    Route::post('/git', 'AdminController@git')->name('admin.git.post');
    Route::get('/users', 'Admin\UserController@list')->name('admin.users');
    Route::get('/user/{id}', 'Admin\UserController@index')->name('admin.user');
    Route::get('/categories', 'Admin\CategoryController@list')->name('admin.categories');
    Route::match(['get', 'post'], '/category/{id?}', 'Admin\CategoryController@edit')->name('admin.category.edit');
    Route::get('/category/{id}/delete', 'Admin\CategoryController@delete')->name('admin.category.delete');
    Route::get('/consultations', 'Admin\ConsultationController@list')->name('admin.consultations');
    Route::match(['get', 'post'], '/consultation/{id}', 'Admin\ConsultationController@index')->name('admin.consultation');

    Route::group(['prefix' => 'product'], function () {
        Route::match(['get', 'post'], '/list', 'Admin\ProductController@list')->name('admin.product.list');
    });
    Route::group(['prefix' => 'pricelist'], function () {
        Route::get('/lapsi', 'Admin\PricelistController@lapsi')->name('admin.pricelist.lapsi');
        Route::group(['prefix' => 'yml'], function () {
            Route::match(['get', 'post'], '/', 'Admin\PricelistController@index')->name('admin.pricelist.index');
            Route::match(['get', 'post'], '/categories/{id}', 'Admin\PricelistController@categories')->name('admin.pricelist.categories');
            Route::match(['get', 'post'], '/products/{id}', 'Admin\PricelistController@uploadProducts')->name('admin.pricelist.products');
        });
        Route::get('/upload-updates', 'Admin\PricelistController@uploadUpdates')->name('admin.pricelist.uploadUpdates');
    });
    Route::group(['prefix' => 'articles'], function () {
        Route::get('/', 'Admin\BlogController@list')->name('admin.articles');
        Route::match(['get', 'post'], '/{id}', 'Admin\BlogController@edit')->name('admin.articles.edit');
    });

    Route::get('/ajax/order', 'OrderController@ajaxGetList')->name('ajax_order_list');
    Route::post('/ajax/getMonthsOrders', 'HomeController@getMonthsOrders')->name('dashboard.getMonthsOrders');
});

app/UserWebsite.php
<?php

namespace App;

use Carbon\Carbon;
use http\Env\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UserWebsite extends Model
{
    protected $table = 'users_websites';

    public $data;

    public function getPaidToAttribute() {
        return new Carbon($this->attributes['paid_to']);
    }

    public function getTariffNameAttribute() {
        return UserWebsiteTariff::find($this->tariff_id)->name;
    }

    public function getStatusNameAttribute() {
        return UserWebsiteStatus::find($this->status_id)->name;
    }

    public function getFUrlAttribute() {
        return ($this->attributes['https'] ? 'https://' : 'http://').$this->attributes['url'];
    }

    public static function getList() {
        return DB::table('users_websites as uw')->join('website_status as ws', 'uw.status_id', '=', 'ws.id')->select('uw.*', 'ws.name as status_name')->paginate(20);
    }

    public static function create($data) {
        DB::table('users_websites')->insert([
            'user_id' => Auth::user()->id,
            'url' => $data['url'],
            'name' => $data['name'],
            'tariff_id' => $data['tariff_id'],
            'status_id' => 1,
        ]);
        return DB::getPdo()->lastInsertId();
    }

    public static function getOwnerId($siteId) {
        $resp = DB::table('users_websites')->select('user_id')->where('id', '=', $siteId)->first();
        if(isset($resp->user_id)) {
            return $resp->user_id;
        } else {
            return null;
        }
    }

    public static function getStatusList() {
        return DB::table('website_status')->get();
    }

    public function setCategories($categories) {
        DB::table('users_website_categories')->where('website_id', '=', $this->id)->delete();
        $_categories = [];
        foreach ($categories as $category) {
            $_categories[] = [
                'website_id' => $this->id,
                'category_id' => $category,
            ];
        }
        DB::table('users_website_categories')->insert($_categories);
    }

    public function categories() {
        $categories = Category::find(array_pluck(DB::table('users_website_categories')->where('website_id', '=', $this->id)->get(), 'category_id'));
        $c = new Category();
        $categories = $c->makeSmallTree($c->prepare($categories));
        return $categories;
    }

    public function getCategories() {
        $categories = DB::table('users_website_categories')->where('website_id', '=', $this->id)->get();
        $_categories = [];
        foreach ($categories as $category) {
            $_categories[$category->category_id] = $category;
        }
        return $_categories;
    }

    public function getProductsList() {
        $categories = array_pluck($this->getCategories(), 'category_id');
        return Product::where('status_id', '=', 1)->where('enabled', '=', 1)->where('count', '>', '0')->whereIn('category_id', $categories)->groupBy('alias')->orderBy('id')->get();
    }

    public function generateApiKey() {
        $this->api_token = substr(encrypt(Carbon::now()), 15, 30);
        $this->save();
    }

    public function getOrders($paginate = 20) {
        return Order::select('orders.*', 'os.name as status_name')
            ->join('order_status as os', 'orders.status_id', '=', 'os.id')
            ->where('orders.website_id', $this->id)
            ->orderBy('orders.id', 'desc')
            ->paginate($paginate);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

}

class UserWebsiteTariff extends Model{
    protected $table = 'website_tariff';
}

class UserWebsiteStatus extends Model{
    protected $table = 'website_status';
}

app/Http/Controllers/Agent/ProductController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Filters\ProductsFilter;
use App\Product;
use App\UserWebsite;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function analytics(Request $request, $website_id)
    {
        if ($request->isMethod('POST')) {
            $website = UserWebsite::find($website_id);
            $client = new Client();
            return json_decode($client->request('POST', $website->f_url . '/index.php?route=extension/feed/yandex_market/mark', [
                'form_params' => [
                    'products' => $request->products,
                    'mark' => $request->mark,
                ],
            ])->getBody());
        }

        $categories = array_pluck(UserWebsite::find($request->route()->id)->getCategories(), 'category_id');
        $products = Product::whereIn('category_id', $categories)->where('enabled', 1);
        $products = (new ProductsFilter($products, $request))->apply()->groupBy('alias')->paginate(20);

        $website = UserWebsite::find($website_id);
        try {
            $client = new Client();
            $pr_ids = implode(', ', array_pluck($products, 'id'));
            try {
                $response = json_decode($client->request('POST', $website->f_url . '/index.php?route=extension/feed/yandex_market/products', [
                    'form_params' => [
                        'page' => 0,
                        'limit' => 500,
                        'where' => ' WHERE `gipu_id` IN (' . $pr_ids . ') ',
                    ],
                ])->getBody());
//                dd($response);
                if(isset($response->products)) {
                    foreach ($response->products as $pr) {
                        $k = array_keys(array_column($products->items(), 'id'), $pr->gipu_id);
                        if (!empty($k))
                            $products[$k[0]]->marked = $pr->marked;
                    }
                }
            } catch (\Exception $ex) {}
        } catch(Exception $ex) {}

        return view('agent.products_analytics', ['products' => $products]);
    }

    public function yml(Request $request, $website_id)
    {
        $website = UserWebsite::find($website_id);

        if ($request->isMethod('POST')) {
            $_data = $request->post();
            foreach ($_data as $k => $v)
                if ($v == null)
                    $_data[$k] = '';

            if ($request['type'] == 'products') {
                $client = new Client();
                $response = json_decode($client->request('POST', $website->f_url . '/index.php?route=extension/feed/yandex_market/' . $_data['to'], [
                    'form_params' => $_data,
                ])->getBody());

                $_products = array();
                foreach ($response->products as $pr) {
                    $pr->price = round($pr->price);
                    $pr->marked = $pr->marked == '1' ? true : false;
                    $_products[$pr->gipu_id] = $pr;
                }

                $response->products = Product::whereIn('id', array_pluck($response->products, 'gipu_id'))->get();
                foreach ($response->products as $k => $product) {
                    $response->products[$k]->opt_price = $response->products[$k]->agent_price;
                    unset($response->products[$k]->agent_price);
                    $response->products[$k]->data = $_products[$product->id];
                }
                return json_encode($response);
            } else {
                $client = new Client();
                $response = json_decode($client->request('POST', $website->f_url . '/index.php?route=extension/feed/yandex_market/' . $_data['to'], [
                    'form_params' => $_data,
                ])->getBody());
                return $response;
            }
        } else {
            return view('agent.yml', ['website' => $website]);
        }
    }

    public function ymlRequest(Request $request, $website_id)
    {

    }
}

app/Http/Controllers/Agent/SettingsController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Image;
use App\UserDocument;
use App\UserRequiredDocument;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use UploadImage;

class SettingsController extends Controller
{
    public function documents() {
        $_documents = Auth::user()->documents()->get();
        $_documents = array_pluck($_documents, 'value', 'document_id');
        $required_documents = UserRequiredDocument::where('juristic_type', Auth::user()->legal_entity)->get();
        return view('agent.settings_document', ['user' => Auth::user(), 'documents' => $_documents,
                                                        'required_documents' => $required_documents]);
    }

    public function documentsUpdate(Request $request) {
        foreach ($request->request as $k => $value) {
            if($k == '_token')
                continue;
            UserDocument::updateOrCreate([
                'user_id' => Auth::user()->id,
                'document_id' => $k,
            ], [
                'value' => $value,
            ]);
        }
        if($request->passport_scan && $request->passport_scan != '') {
            UserDocument::updateOrCreate([
                'user_id' => Auth::user()->id,
                'document_id' => 22,
            ], [
                'value' => Image::upload($request->passport_scan),
            ]);
        }
        return redirect(route('agent.settings.documents'));
    }

    public function changeJuristic() {
        $user = Auth::user();
        $user->legal_entity = !$user->legal_entity;
        $user->save();
        return redirect(route('agent.settings.documents'));
    }
}

resources/views/agent/partners.blade.php
@extends('layouts.app')

@section('content')
  <h1 class="h3 mb-4 text-gray-800">Партнерская программа</h1>
  <div class="row">
    <div class="col-xl-3 col-md-12 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Ваша партнерская ссылка
                <span class="toolt" data-toggle="tooltip"
                      title="Ваша партнерская ссылка может вести на любую из основных страниц сайта. Например на страницу описания тарифов: https://gipo.ru/tariff?ref={{ 380400 + auth()->user()->id }}">?</span>
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                <input type="text" value="https://gipo.ru?ref={{ 380400 + auth()->user()->id }}" class="form-control"
                       style="font-size: 14px;" readonly>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-handshake fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Подключено пользователей</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                {{ count($partners) }}
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-user-friends fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Подключено сайтов</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                {{ $wc }}
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-globe fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Мои партнеры</h6>
    </div>
    <div class="card-body">
      <div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
              <th>Имя пользователя</th>
              <th>Дата подключения</th>
              <th>Сайты пользователя</th>
            </tr>
            </thead>
            <tbody>
            @if(count($partners) > 0)
              @foreach($partners as $user)
                <tr>
                  <td>{{ $user->first_name }} {{ $user->second_name }}</td>
                  <td>{{ $user->created_at }}</td>
                  <td>
                    @if(count($user->websites()) > 0)
                      @foreach($user->websites() as $wes)
                        <a href="http://{{$wes->url}}" target="_blank">{{ $wes->url }}</a> <i class="text-xs">({{ $wes->status_name }})</i>,
                      @endforeach
                    @else
                      <i>нет сайтов</i>
                    @endif
                  </td>
                </tr>
              @endforeach
            @else
              <tr>
                <td colspan="3">
                  <h4 class="text-center">Подключенных партнеров нет</h4>
                </td>
              </tr>
            @endif
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('styles')
  <style>
    .toolt {
      border: 2px solid #597be1;
      padding: 2px;
      border-radius: 50%;
      width: 16px;
      height: 16px;
      display: inline-block;
      text-align: center;
      line-height: 10px;
      margin-left: 3px;
    }
  </style>
@endpush

@push('scripts')
  <script>
      $(function () {
          $('[data-toggle="tooltip"]').tooltip()
      })
  </script>
@endpush

resources/views/agent/tariff.blade.php
@extends('layouts.app')

@section('content')
  <h1 class="h1 mb-5 text-center text-gray-800">Выберите подходящий вам тарифный план</h1>
  <div class="row justify-content-md-center">
    <div class="pricing card-deck flex-column flex-md-row mb-3 col-xl-9">
      @foreach($tariffs as $k => $t)
        <div class="card card-pricing text-center px-3 mb-4 col-md-6 {{ $k == 2 ? 'popular shadow' : '' }}">
            <span
              class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">{{ $t['name'] }}</span>
          <div class="bg-transparent card-header pt-4 border-0">
            <h1 class="h1 font-weight-normal text-primary text-center mb-0" data-pricing-value="15"><span
                class="price">{{ $t['price'] }}</span><span class="fa fa-ruble-sign"
                                                            style="font-size: 24px;"></span><span
                class="h6 text-muted ml-2">/ в год</span></h1>
          </div>
          <div class="card-body pt-0">
            <ul class="list-unstyled mb-4">
              @foreach($t['features'] as $f)
                <li>{{ $f['name'] }}</li>
              @endforeach
            </ul>
            <a href="{{ route('agent.website.create.setup', [ 'tariff' => $k ]) }}"
               class="btn btn-{{ $k == 2 ? 'primary' : 'outline-secondary' }} mb-3">Заказать</a>
          </div>
        </div>
      @endforeach
    </div>
  </div>
@endsection

@push('styles')
  <style>
    .pricing {
      align-items: flex-start;
    }
    .card-pricing.popular {
      z-index: 1;
      border: 3px solid #4e73df;
    }

    .card-pricing .list-unstyled li {
      padding: .5rem 0;
      color: #6c757d;
    }
  </style>
@endpush

resources/views/agent/website.blade.php
@extends('layouts.app')

@section('content')
  <h1 class="h3 mb-4 text-gray-800">{{ $website->name }}
    <small>
      <a href="{{ $website->url != '' ? 'http://'.$website->url : '' }}"
         target="_blank">{{ $website->url != '' ? '('.$website->url.')' : '' }}</a>
    </small>
  </h1>
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Управление сайтом</h6>
    </div>
    <div class="card-body">

      @if (session('status'))
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
      @endif
      <div>
        @if($website->status_id == 1)
          <h2 class="text-center">Для начала работы необходимо оплатить тариф</h2>
          <p class="text-center">Для оплаты свяжитесь с менеджером сервиса</p>
        @elseif($website->status_id == 3)
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Id</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="{{ $website->id }}">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Статус</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" value="{{ $website->status_name }}">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Оплачен до</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext"
                     value="{{ $website->paid_to->format('d.m.Y') }}">
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Текущий тариф</label>
            <div class="col-sm-10">
              <span class="btn btn-primary btn-sm">{{ $website->tariff_name }}</span>
              @if($website->tariff_id != 3)
                <a href="#!" class="btn btn-success btn-sm" title="Повысить тариф"><span
                    class="fa fa-level-up-alt"></span></a>
              @endif
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Ваш api-ключ</label>
            <div class="col-sm-10">
              <input type="text" readonly value="{{ $website->api_token or 'Не создан' }}"
                     class="form-control form-control-sm" style="display: inline-block;width: unset">
              <btn class="btn btn-primary btn-sm" data-toggle="modal" data-target="#new-token">Генерировать новый
              </btn>
            </div>
          </div>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label">Наценка на опт. цену</label>
            <form action="{{ route('agent.website.setOptMarkup', request()->id) }}" method="POST" class="col-sm-10">
              {{ csrf_field() }}
              <div class="input-group">
                <input type="number" min="0" class="form-control col-lg-1 col-sm-2"
                       value="{{ $settings['opt_markup']->value or $settings['opt_markup']->def }}" name="markup">
                <div class="input-group-append">
                  <div class="input-group-text">%</div>
                </div>
                <input type="submit" class="btn btn-primary ml-1" value="Сохранить"></input>
              </div>
            </form>
          </div>
          <a href="{{ route('agent.product.analytics', request()->id) }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-chart-area"></i>
                    </span>
            <span class="text">Аналитика цен</span>
          </a>
          <a href="{{ route('agent.product.yml', request()->id) }}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-list"></i>
                    </span>
            <span class="text">Выгрузка yml</span>
          </a>
        @else
          <h3 class="text-center">Вебсайт {{ $website->status_name }}</h3>
        @endif
      </div>
    </div>
  </div>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">История заказов</h6>
    </div>
    <div class="card-body">
      <div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
              <th style="width: 1%;">№</th>
              <th>Id заказа в вашем магазине</th>
              <th>Сумма</th>
              <th>Статус заказа</th>
              <th>Дата обновления</th>
              <th>Дата добавления</th>
            </tr>
            </thead>
            <tbody>
            @if($orders)
              @foreach($orders as $order)
                <tr>
                  <td>{{ $order->id }}</td>
                  <td>{{ $order->website_order_local_id }}</td>
                  <td>{{ $order->order_data->totals[2]->value }}</td>
                  <td>{{ $order->status_name }}</td>
                  <td>{{ $order->updated_at }}</td>
                  <td>{{ $order->created_at }}</td>
                </tr>
              @endforeach
            @else
              <tr>
                <td colspan="5">
                  <h5>Заказов в этом магазине пока что нет</h5>
                </td>
              </tr>
            @endif
            </tbody>
          </table>
          @if($orders)
            {{ $orders->links() }}
          @endif
        </div>
      </div>
    </div>
  </div>
@endsection

@push('modals')
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
       aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="new-token" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Генерация нового api-ключа</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p><b>Внимание!</b> При генерации нового api ключа, <b>прошлый api-ключ будет неработоспособен.</b> Не
            забудьте обновить api-ключ в модуле синхронизации товаров в вашем интернет-магазине.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Отмена</button>
          <a href="{{ route('agent.website.generateApiToken', ['id' => $website->id]) }}"
             class="btn btn-danger btn-icon-split">
            <span class="icon text-white-50">
              <i class="fa fa-sync-alt"></i>
            </span>
            <span class="text">Сгенерировать новый</span>
          </a>
        </div>
      </div>
    </div>
  </div>
@endpush

@push('scripts')
  <script>
      $('#generate-token').click(function (e) {
          e.preventDefault();
      });
  </script>
@endpush