routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

//основые страницы сайта
Route::group(['prefix' => '/', 'middleware' => ['referral']], function(){

    Route::get('/', function () {
        return view('landing');
    });
    Route::get('/dropshipping', function () {
        return view('landingDropshipping');
    });
    Route::get('/about', function () {
        return view('about');
    });
    Route::get('/tariff', function () {
        return view('tariff');
    });


    Route::group(['prefix' => 'blog'], function () {
        Route::get('/', 'WebsiteController@articles')->name('articles');
        Route::match(['get', 'post'], '/{id}', 'WebsiteController@article')->name('article');
    });

});

Route::get('/telegram/'.\App\Telegram\TelegramBot::$token, 'TelegramBotController@index')->name('telegram.api');


Route::get('/mail', 'MailController@send')->name('mail.send');


Route::post('/create-consultation-request', 'WebsiteController@createConsultationRequest')->name('createConsultationRequest');

Auth::routes();

//личный кабинет
Route::get('/home/new', 'HomeController@new')->middleware('auth')->name('agent.new');
Route::group(['prefix' => 'home', 'middleware' => ['auth', 'userOnline']], function(){ //, 'documents'

    Route::get('/', 'HomeController@index')->name('agent.home');
    Route::get('/website/create', 'Agent\WebsiteController@createPage')->name('agent.website.create');
    Route::get('/website/create/setup', 'Agent\WebsiteController@setup')->name('agent.website.create.setup');
    Route::post('/website/create/setup/categories', 'Agent\WebsiteController@selectCategories')->name('agent.website.create.setup.selectCategories');

    Route::group(['prefix' => 'website', 'middleware' => ['isUserWebsite']], function () {
        Route::get('/{id}', 'Agent\WebsiteController@index')->name('agent.website');
        Route::get('/{id}/generate-token', 'Agent\WebsiteController@generateApiToken')->name('agent.website.generateApiToken');
        Route::post('/{id}/set-markup', 'Agent\WebsiteController@setOptMarkup')->name('agent.website.setOptMarkup');
        Route::match(['get', 'post'], '/{id}/analytics', 'Agent\ProductController@analytics')->name('agent.product.analytics');
        Route::match(['get', 'post'], '/{id}/yml', 'Agent\ProductController@yml')->name('agent.product.yml');
    });

    Route::group(['prefix' => 'wallet'], function() {
        Route::get('/', 'Agent\WalletController@index')->name('agent.wallet');
        Route::post('/', 'Agent\WalletController@createWidtdrawRequest')->name('agent.wallet.createWidtdrawRequest');
    });

    Route::group(['prefix' => 'settings'], function() {
        Route::get('/documents', 'Agent\SettingsController@documents')->name('agent.settings.documents');
        Route::post('/documents-update', 'Agent\SettingsController@documentsUpdate')->name('agent.settings.documents.update');
        Route::get('/change-juristic', 'Agent\SettingsController@changeJuristic')->name('agent.settings.changeJuristic');
    });

    Route::get('/partners', 'HomeController@partners')->name('agent.partners');
});

//админка
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'isAdmin', 'userOnline']], function(){
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::get('/orders', 'AdminController@orders')->name('orders');
    Route::get('/order/{id}', 'OrderController@index')->name('order');
    Route::post('/order/{id}', 'OrderController@addHistory')->name('order_post');
    Route::get('/order/{id}/print', 'OrderController@print')->name('order.print');
    Route::get('/websites', 'Admin\WebsiteController@list')->name('admin.websites');
    Route::match(['get', 'post'], '/website/{id}', 'Admin\WebsiteController@edit')->name('admin.website.edit');
    Route::match(['get', 'post'], '/website/{id}/categories', 'Admin\WebsiteController@categories')->name('admin.website.categories');
    Route::post('/website/{id}/prolong', 'Admin\WebsiteController@prolong')->name('admin.website.prolong');
    Route::get('/widthdraw-requests', 'AdminController@widthdrawRequests')->name('admin.widthdrawRequests');
    Route::get('/widthdraw-request/{id}', 'AdminController@widthdrawRequest')->name('admin.widthdrawRequest');
    Route::post('/widthdraw-request/{id}', 'AdminController@updateWidthdrawRequestStatus')->name('admin.updateWidthdrawRequestStatus');
    Route::get('/git', 'AdminController@git')->name('admin.git');
    Route::post('/git', 'AdminController@git')->name('admin.git.post');
    Route::get('/users', 'Admin\UserController@list')->name('admin.users');
    Route::get('/user/{id}', 'Admin\UserController@index')->name('admin.user');
    Route::get('/categories', 'Admin\CategoryController@list')->name('admin.categories');
    Route::match(['get', 'post'], '/category/{id?}', 'Admin\CategoryController@edit')->name('admin.category.edit');
    Route::get('/category/{id}/delete', 'Admin\CategoryController@delete')->name('admin.category.delete');
    Route::get('/consultations', 'Admin\ConsultationController@list')->name('admin.consultations');
    Route::match(['get', 'post'], '/consultation/{id}', 'Admin\ConsultationController@index')->name('admin.consultation');

    Route::group(['prefix' => 'product'], function () {
        Route::match(['get', 'post'], '/list', 'Admin\ProductController@list')->name('admin.product.list');
    });
    Route::group(['prefix' => 'pricelist'], function () {
        Route::get('/lapsi', 'Admin\PricelistController@lapsi')->name('admin.pricelist.lapsi');
        Route::group(['prefix' => 'yml'], function () {
            Route::match(['get', 'post'], '/', 'Admin\PricelistController@index')->name('admin.pricelist.index');
            Route::match(['get', 'post'], '/categories/{id}', 'Admin\PricelistController@categories')->name('admin.pricelist.categories');
            Route::match(['get', 'post'], '/products/{id}', 'Admin\PricelistController@uploadProducts')->name('admin.pricelist.products');
        });
        Route::get('/upload-updates', 'Admin\PricelistController@uploadUpdates')->name('admin.pricelist.uploadUpdates');
    });
    Route::group(['prefix' => 'articles'], function () {
        Route::get('/', 'Admin\BlogController@list')->name('admin.articles');
        Route::match(['get', 'post'], '/{id}', 'Admin\BlogController@edit')->name('admin.articles.edit');
    });

    Route::get('/ajax/order', 'OrderController@ajaxGetList')->name('ajax_order_list');
    Route::post('/ajax/getMonthsOrders', 'HomeController@getMonthsOrders')->name('dashboard.getMonthsOrders');
});

app/Product.php
<?php

namespace App;

use App\Filters\ProductsFilter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    protected $connection = 'main';
    protected $table = 'products';
    public $timestamps = false;

    private $_provider_info = null;

    public function getImagesAttribute() {
        return $this->hasMany('app\ProductImage', 'product_id')->get();
    }

    public function getImageAttribute() {
        $img = $this->hasOne('app\ProductImage', 'product_id')->first();
        if($img) {
            return $img->image;
        }
        return '';
    }

    public function getNameAttribute() {
        return trim($this->attributes['name']);
    }


    public static $markup = null;
    public function makeValues() {
        if(self::$markup == null) {
            self::$markup = request()->user->setting('1', request()->user->id);
        }
        $markup = self::$markup;
        if($markup->value != null && $markup->value != 0) {
            $_price = $this->agent_price * ((100 + $markup->value) / 100);
        } else {
            $_price = $this->recommended_price;
        }
        return [
            'id' => $this->id,
            'name' => $this->name,
            'category_id' => $this->category_id,
            'price' => $_price,
            'purchase_price' => $this->agent_price,
            'images' => array_pluck($this->images, 'image'),
            'alias' => $this->alias,
            'availability' => $this->count,
            'status' => $this->status_id,
        ];
    }
    public function makeAllValues() {
        if(self::$markup == null) {
            self::$markup = request()->user->setting('1', request()->user->id);
        }
        $markup = self::$markup;
        if($markup->value != null && $markup->value != 0) {
            $_price = $this->agent_price * ((100 + $markup->value) / 100);
        } else {
            $_price = $this->recommended_price;
        }
        return [
            'id' => $this->id,
            'name' => $this->name,
            'category_id' => $this->category_id,
            'price' => $_price,
            'purchase_price' => $this->agent_price,
            'images' => array_pluck($this->images, 'image'),
            'alias' => $this->alias,
            'availability' => $this->count,
            'status' => $this->status_id,
        ];
    }

    public function properties() {
        $_properties = DB::connection('main')
            ->table('property_value as pv')
            ->select('pv.*', 'pe.value as e_value')
            ->leftJoin('property_enum as pe', 'pe.id', '=', 'pv.value_enum')
            ->where('product_id', $this->id)->get();
        // dd($_propertires);
        $properties = [];
        foreach ($_properties as $prop) {
            $properties[$prop->id] = [
                'id' => $prop->id,
                'property_id' => $prop->property_id,
                'product_id' => $prop->product_id,
                'value' => $prop->type == 'enum' ? $prop->e_value : $prop->value,
                'description' => $prop->description,
            ];
        }
        return $properties;
    }

    public function getProviderInfoAttribute() {
        $this->_provider_info;
        if($this->_provider_info)
            return $this->_provider_info;
        else
            $this->_provider_info = ProductProvider::where('gipo_index', $this->id)->first();
//            ->join('product_owners', 'product.id', '=', 'product_owners.product_id');
        return $this->_provider_info;
    }


}

class ProductImage extends Model {
    protected $connection = 'main';
    protected $table = 'product_images';

    public function getImageAttribute() {
        return trim($this->attributes['image']);
    }
}

class ProductProvider extends Model {
    protected $connection = 'pricelists';
    protected $table = 'product';

    public function getNameAttribute() {
        return $this->attributes['Name'];
    }
}

class ProductProperties extends Model {
    protected $connection = 'main';
    protected $table = 'properties';
    public $timestamps = false;
}

class ProductPropertyValue extends Model {
    protected $connection = 'main';
    protected $table = 'property_value';
    public $timestamps = false;
}

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    private $wallet = null;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'second_name', 'phone', 'email', 'password', 'last_activity', 'referral'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPhoneAttribute($val)
    {
        $this->attributes['phone'] = '7' . $val;
    }

    public function getLastActivityAttribute() {
        return new Carbon($this->attributes['last_activity']);
    }

    public function getIsOnlineAttribute() {
        return $this->last_activity->diffInMinutes(Carbon::now()) < 5;
    }

    public $documents = null;
    public $websites = null;

    public function documents()
    {
        return $this->hasMany('App\UserDocument');
    }

    public function websites()
    {
        if ($this->websites)
            return $this->websites;
        $this->websites = DB::table('users_websites as uw')->join('website_status as ws', 'ws.id', '=', 'uw.status_id')
            ->select('uw.*', 'ws.name as status_name')->where('user_id', '=', $this->id)->orderBy('id')->get();
        return $this->websites;
    }

    public function wallet()
    {
        if (!$this->wallet) {
            $this->wallet = new UserWallet($this);
        }
        return $this->wallet;
    }

    public function status() {
        return $this->belongsTo('App\UserStatus');
    }

    public function setting($id, $user_id = null) {
        if($user_id == null)
            $user_id = Auth::user()->id;
        $setting = UserSetting::find($id);
        $t = UserSettingValue::where('setting_id', $setting->id)->where('user_id', $user_id)->first();
        $setting->value = $t != null ? $t->value : $t;
        return $setting;
    }

    public function partners() {
        return User::where('referral', Auth::user()->id)->get();
    }

    public function isAdmin() {
        if(Auth::user() && Auth::user()->role_id == 0)
            return true;
        else
            return false;
    }

}

class UserDocument extends Model
{
    protected $table = 'users_documents';

    protected $fillable = array('user_id', 'document_id', 'value');

    public $timestamps = false;
}

class UserRequiredDocument extends Model
{
    protected $table = 'users_required_documents';

    public $timestamps = false;
}

class UserStatus extends Model
{
    protected $table = 'users_status';

    public $timestamps = false;
}

class UserSetting extends Model
{
    protected $table = 'user_settings';

    public $timestamps = false;
}

class UserSettingValue extends Model
{
    protected $table = 'user_setting_values';

    protected $fillable = ['user_id', 'setting_id', 'value'];

    public $timestamps = false;
}

resources/views/admin/categories.blade.php
@extends('admin.layouts.app')

@section('content')
  <h2 class="h3 mb-4 text-gray-800">Управление категориями</h2>
  <ul class="list-group">
    @include('admin.partials.category', ['categories' => $categories])
    <div class="mt-2">
      <a href="{{ route('admin.category.edit') }}" class="btn btn-dark text-xs">Добавить сюда</a>
    </div>
  </ul>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app')

@section('content')
  <div class="panel panel-default">
    <div class="panel-heading">Панель управления</div>

    <div class="panel-body">
      @if (session('status'))
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
      @endif

      {{Auth::user()->first_name}}, добро пожаловать обратно!
    </div>
  </div>
@endsection

resources/views/admin/products.blade.php
@extends('admin.layouts.app')

@section('content')
  <div class="row">
    <div class="mb-4 col-md-8 col-xl-9">
      <div class="shadow card">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Список товаров</h6>
        </div>
        <div class="card-body">
          @if (session('status'))
            <div class="alert alert-success">
              {{ session('status') }}
            </div>
          @endif
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th></th>
                <th>id</th>
                <th>Наименование</th>
                <th>Вкл</th>
                <th>Остаток</th>
                <th>Приход</th>
                <th>Опт</th>
                <th>Агентская</th>
                <th>РРЦ</th>
                <th>ЯМ</th>
                <th>Разница</th>
              </tr>
              </thead>
              <tbody>
              @foreach($products as $product)
                <tr
                  class="{{ $product->yandex_minimal_price > 0 && $product->agent_price > 0 && $product->agent_price / $product->yandex_minimal_price > 1 ? '' : 'border-right-success' }}">
                  <td>
                    <img src="{{ $product->image }}" alt="" style="max-height: 50px;max-width: 50px;">
                  </td>
                  <td>{{ $product->id }}</td>
                  <td>{{ $product->name }} <span style="font-size: .8em;"><i>{{ $product->provider_info->provider_id or 'нет' }}</i> {{ $product->provider_info->name or 'нет' }}</span></td>
                  <td>
                    <select data-gipo-id="{{ $product->id }}" class="custom-select status_select" style="width: 70px;">
                      <option value="0" {{ $product->enabled ? '' : 'selected' }}>Нет</option>
                      <option value="1" {{ $product->enabled ? 'selected' : '' }}>Да</option>
                    </select>
                  </td>
                  <td>{{ $product->count }}</td>
                  <td>{{ $product->in_transit }}</td>
                  <td>{{ $product->opt_price }}</td>
                  <td>{{ $product->agent_price }}</td>
                  <td>{{ $product->recommended_price }}</td>
                  <td>{{ $product->yandex_minimal_price }}</td>
                  <td>{{ $product->yandex_minimal_price > 0 && $product->agent_price > 0 ? (100 * round(1 - ($product->agent_price / $product->yandex_minimal_price), 2)) : 0 }}% ({{ $product->agent_price - $product->yandex_minimal_price }})</td>
                  <td>
                    <a href="https://market.yandex.ru/product--/{{ $product->yandex_id or '' }}" target="_blank" class="fab fa-yandex btn btn-primary btn-circle btn-sm"></a>
                  </td>
                </tr>
              @endforeach
              </tbody>
            </table>
            {{ $products->appends($_GET)->links() }}
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-4">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary"><span class="fa fa-cog"></span> Фильтр</h6>
        </div>
        <div class="card-body">
          <form action="">
            <div class="form-group">
              <label for="id">ID</label>
              <input type="number" class="form-control" id="id" name="id" min="1" value="{{ request('id') or '' }}">
            </div>
            <div class="form-group">
              <label for="name">Наименование</label>
              <input type="text" class="form-control" id="name" name="name" minlength="3" value="{{ request('name') }}">
            </div>
            <div class="form-group">
              <label for="method">Сортировать</label>
              <select class="custom-select" name="method" id="method">
                <option>Стандартно</option>
                <option value="1" {{ request('method') == 1 ? 'selected' : '' }}>Наибольший заработок, %</option>
                <option value="2" {{ request('method') == 2 ? 'selected' : '' }}>Наибольший заработок, Р</option>
              </select>
            </div>
            <button class="btn btn-primary">Показать</button>
            <a href="{{ route('admin.product.list') }}" class="btn btn-danger"><i class="fa fa-times"></i></a>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('scripts')
  <script>
    $('.status_select').change(function (e) {
        var id = $(this).data('gipo-id');
        var val = $(this).val();
        $.ajax({
            url: '',
            type: 'POST',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            data: {
                product_id: id,
                enabled: val,
            },
            success: function (resp) {
                console.log(resp);
            },
            error: function (resp) {
                console.log(resp);
            }
        });
    });
  </script>
@endpush

resources/views/admin/user.blade.php
@extends('admin.layouts.app')

@section('content')
  <h1 class="h3 mb-4 text-gray-800">Управление пользователем <span
      class="btn btn-sm btn-{{ $user->status_id == 4 ? 'success' : 'primary' }}">{{ $user->status->name }}</span></h1>
  @if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>
  @endif
  <div class="row" style="font-size: 15px;">
    <div class="col-12 col-xl-4">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary"><span class="fa fa-user"></span> Общая информация</h6>
        </div>
        <div class="card-body">
          <table class="table">
            <tbody>
            <tr>
              <td>
                <button class="btn btn-info btn-sm text-xs">Имя</button>
              </td>
              <td>{{ $user->first_name }} {{ $user->second_name }}</td>
            </tr>
            <tr>
              <td>
                <button class="btn btn-info btn-sm text-xs">Почта</button>
              </td>
              <td>{{ $user->email }} <span class="text-xs">({{ $user->email_confirmed == 1 ? 'подтверждена' : 'не подтверждена' }})</span>
              </td>
            </tr>
            <tr>
              <td>
                <button class="btn btn-info btn-sm text-xs">Телефон</button>
              </td>
              <td>{{ $user->phone }} <span class="text-xs">({{ $user->phone_confirmed == 1 ? 'подтвержден' : 'не подтвержден' }})</span>
              </td>
            </tr>
            <tr>
              <td>
                <button class="btn btn-info btn-sm text-xs">Юр. статус</button>
              </td>
              <td>{{ $user->legal_entity == 1 ? 'Юридическое лицо' : 'Физическое лицо' }}</td>
            </tr>
            <tr>
              <td>
                <button class="btn btn-info btn-sm text-xs">Текущий баланс</button>
              </td>
              <td>{{ $user->wallet()->balance() }}руб.</td>
            </tr>
            <tr>
              <td>
                <button class="btn btn-info btn-sm text-xs">Зарегистрирован</button>
              </td>
              <td>{{ $user->created_at }}</td>
            </tr>
            <tr>
              <td>
                <button class="btn btn-info btn-sm text-xs">Был в сети</button>
              </td>
              <td class="{{ $user->is_online ? 'text-success' : '' }}">{{ $user->is_online ? 'Онлайн' : $user->last_activity }}</td>
            </tr>
            </tbody>
          </table>
          <a href="#" class="btn btn-success btn-sm btn-icon-split ml-2">
                    <span class="icon text-white">
                      <i class="fas fa-id-card"></i>
                    </span>
            <span class="text">Паспортные данные</span>
          </a>
          <a href="#" class="btn btn-success btn-sm btn-icon-split">
                    <span class="icon text-white">
                      <i class="fas fa-folder"></i>
                    </span>
            <span class="text">Документы</span>
          </a>
        </div>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-xl-8">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary"><span class="fa fa-money-check"></span> Информация о балансе</h6>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th>№</th>
                <th>Статус</th>
                <th>Сумма</th>
                <th>Создан</th>
                <th>Ответ</th>
              </tr>
              </thead>
              <tbody>
                @if($withdrawRequests)
                  @foreach($withdrawRequests as $req)
                    <tr>
                      <td>
                        <a href="{{ route('admin.widthdrawRequest', ['id' => $req->id]) }}">{{ $req->id }}</a>
                      </td>
                      <td>{{ $req->status->name or 'Не установлен' }}</td>
                      <td>{{ $req->sum }}</td>
                      <td>{{ $req->created_at }}</td>
                      <td>{{ $req->updated_at }}</td>
                    </tr>
                  @endforeach
                @endif
              </tbody>
            </table>
            @if($withdrawRequests)
              {{ $withdrawRequests->links() }}
            @endif
          </div>
        </div>
      </div>
    </div>
    <div class="col-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary"><span class="fa fa-search-dollar"></span> История транзакций
          </h6>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th>№ транзакции</th>
                <th>Тип транзакции (№ заказа)</th>
                <th>Сумма</th>
                <th>Дата</th>
              </tr>
              </thead>
              <tbody>
              @if(count($transactions) > 0)
                @foreach($transactions as $transaction)
                  <tr
                    class="{{ $transaction->transaction_data->summ > 0 ? "border-left-success" : "border-left-danger" }}">
                    <td>{{ $transaction->id }}</td>
                    <td>{{ $transaction->type->name or '' }}
                      @if(isset($transaction->transaction_data->transaction->website_id))
                        (<a
                          href="{{ route('admin.website.edit', ['id' => $transaction->transaction_data->transaction->website_id]) }}">
                          вебсайт id{{ $transaction->transaction_data->transaction->website_id or '' }}
                        </a>)
                        (<a
                          href="{{ route('order', ['id' => $transaction->transaction_data->transaction->id]) }}">
                          заказ id{{ $transaction->transaction_data->transaction->id or '' }}
                        </a>)
                      @endif
                    </td>
                    <td>{{ $transaction->transaction_data->summ }}</td>
                    <td>{{ $transaction->created_at }}</td>
                  </tr>
                @endforeach
              @else
                <tr>
                  <td colspan="4">
                    <h4 class="text-center">История транзакций пользователя пока что пуста</h4>
                  </td>
                </tr>
              @endif
              </tbody>
            </table>
            @if($transactions)
              {{ $transactions->links() }}
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@push('modals')
  <div class="modal fade" tabindex="-1" role="dialog" id="modal-documents">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Введенные данные пользователя</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{--@foreach(dd($user->documents))--}}

          {{--@endforeach--}}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>
@endpush

@push('scripts')
  <script>

  </script>
@endpush
@push('styles')
  <style>
    .table {
      margin-bottom: 0;
    }

    .table tr:first-child td {
      border-top: none;
    }
  </style>
@endpush

resources/views/admin/users.blade.php
@extends('admin.layouts.app')

@section('content')
  <h1 class="h3 mb-4 text-gray-800">Управление Сайтами</h1>
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Сайты агентов</h6>
    </div>
    <div class="card-body" id="orders-list">

      @if (session('status'))
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
      @endif
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>ID пользователя</th>
            <th>Имя пользователя</th>
            <th>Почтовый адрес</th>
            <th>Статус</th>
            <th>Был в сети</th>
            <th>Действие</th>
          </tr>
          </thead>
          <tbody>
          @foreach($users as $user)
            <tr>
              <td>{{ $user->id }}</td>
              <td>{{ $user->first_name }} {{ $user->second_name }}</td>
              <td>{{ $user->email }}</td>
              <td>{{ $user->status->name }}</td>
              <td class="{{ $user->is_online ? 'text-success' : '' }}">{{ $user->is_online ? 'Онлайн' : $user->last_activity->diffForHumans() }}</td>
              <td>
                <a href="{{ route('admin.user', ['id' => $user->id]) }}" class="btn btn-primary"><span
                    class="fa fa-eye"></span></a>
              </td>
            </tr>
          @endforeach
          </tbody>
        </table>
        {{ $users->links() }}
      </div>
    </div>
  </div>


  {{--<div class="panel panel-default">--}}
    {{--<div class="panel-heading">Управление заказами</div>--}}

    {{--<div class="panel-body" id="orders-list">--}}
      {{--@if (session('status'))--}}
        {{--<div class="alert alert-success">--}}
          {{--{{ session('status') }}--}}
        {{--</div>--}}
      {{--@endif--}}
      {{--<div class="table-responsive">--}}
        {{--<table class="table table-striped table-hover">--}}
          {{--<thead>--}}
            {{--<tr>--}}
              {{--<th>ID сайта</th>--}}
              {{--<th>ID владельца</th>--}}
              {{--<th>URL сайта</th>--}}
              {{--<th>Статус сайта</th>--}}
              {{--<th>Действие</th>--}}
            {{--</tr>--}}
          {{--</thead>--}}
          {{--<tbody>--}}
          {{--@foreach($websites as $website)--}}
            {{--<tr>--}}
              {{--<td>{{ $website->id }}</td>--}}
              {{--<td>{{ $website->user_id }}</td>--}}
              {{--<td>{{ $website->url }}</td>--}}
              {{--<td>{{ $website->status_name }}</td>--}}
              {{--<td>--}}
                {{--<a href="{{ route('admin.website.edit', ['id' => $website->id]) }}" class="btn btn-primary"><span--}}
                    {{--class="glyphicon glyphicon-eye-open"></span></a>--}}
              {{--</td>--}}
            {{--</tr>--}}
            {{--@endforeach--}}
          {{--</tbody>--}}
        {{--</table>--}}
        {{--{{ $websites->links() }}--}}
      {{--</div>--}}
    {{--</div>--}}
  {{--</div>--}}
@endsection